---
deployment:
  tasks:
    - export DEPLOYPATH=/home/codj2387/public_html/
    # - /bin/cp public/index.php $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    # - /bin/cp/public -R demo $DEPLOYPATH
    # - /bin/cp style.css $DEPLOYPATH